//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ada
    {
        public int ada_id { get; set; }
        public int tapuMahalle_id { get; set; }
        public int adaNo { get; set; }
        public string aciklama { get; set; }
    
        public virtual tapuMahalle tapuMahalle { get; set; }
    }
}
