//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bagimsiz
    {
        public int bagimsiz_id { get; set; }
        public Nullable<int> bina_id { get; set; }
        public Nullable<int> il_id { get; set; }
        public Nullable<int> ilce_id { get; set; }
        public Nullable<int> mahalle_id { get; set; }
        public Nullable<int> tapuMahalle_id { get; set; }
        public Nullable<int> caddeSokak_id { get; set; }
        public Nullable<int> ada_id { get; set; }
        public Nullable<int> parsel_id { get; set; }
        public Nullable<int> malik_id { get; set; }
        public string kullanimTürü { get; set; }
        public Nullable<decimal> bagimsizAlani { get; set; }
        public string nitelik { get; set; }
        public string elektrikNo { get; set; }
        public string suNo { get; set; }
        public string isinmaTürü { get; set; }
        public string dogalGazNo { get; set; }
        public string yapiKayitBelgesi { get; set; }
        public string bagimsizNo { get; set; }
        public string katNo { get; set; }
        public string cephe { get; set; }
        public string manzara { get; set; }
        public Nullable<int> odaSayisi { get; set; }
        public Nullable<int> banyoSayisi { get; set; }
        public string mutfakTipi { get; set; }
        public Nullable<int> balkon { get; set; }
        public Nullable<decimal> metreKareBirimFiyat { get; set; }
        public Nullable<decimal> toplamBedel { get; set; }
        public string hisseDurum { get; set; }
        public string esyaDurum { get; set; }
        public string aidat { get; set; }
        public string konutTipi { get; set; }
        public string murfakTipi { get; set; }
        public string durum { get; set; }
    }
}
