//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bagimsiz
    {
        public int bagimsiz_id { get; set; }
        public int tasinmaz_id { get; set; }
        public string bagimsizNo { get; set; }
        public string kullanımTürü { get; set; }
        public string odaSayısı { get; set; }
        public bool balkon { get; set; }
        public bool esyaDurumu { get; set; }
        public string cephe { get; set; }
        public string nitelik { get; set; }
        public string elektrik { get; set; }
        public string su { get; set; }
        public string dogalGaz { get; set; }
        public decimal rayicBedel { get; set; }
    
        public virtual tasinmaz tasinmaz { get; set; }
    }
}
