//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class malik
    {
        public int malik_id { get; set; }
        public Nullable<int> parsel_id { get; set; }
        public Nullable<int> ada_id { get; set; }
        public Nullable<int> bina_id { get; set; }
        public Nullable<int> bagimsiz_id { get; set; }
        public string parselNo { get; set; }
        public Nullable<int> hissePay { get; set; }
        public Nullable<int> hissePayda { get; set; }
        public Nullable<int> hisseMiktarı { get; set; }
        public Nullable<System.DateTime> hisseEdinmeTarih { get; set; }
        public string hisseEdinmeNedeni { get; set; }
        public string beyan { get; set; }
        public string beyanYevmiyeNo { get; set; }
        public Nullable<System.DateTime> beyanYevmiyeTarih { get; set; }
        public string haciz { get; set; }
        public string hacizYevmiyeNo { get; set; }
        public Nullable<System.DateTime> hacizYevmiyeTarih { get; set; }
        public Nullable<int> mahkeme { get; set; }
        public string malikAd { get; set; }
        public string malikSoyad { get; set; }
        public Nullable<int> malikTc { get; set; }
        public string malikBabaAdi { get; set; }
        public Nullable<int> malikTelNo { get; set; }
    
        public virtual bagimsiz bagimsiz { get; set; }
        public virtual bina bina { get; set; }
        public virtual parsel parsel { get; set; }
    }
}
