//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CityExperDbEntities : DbContext
    {
        public CityExperDbEntities()
            : base("name=CityExperDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ada> ada { get; set; }
        public virtual DbSet<bagimsiz> bagimsiz { get; set; }
        public virtual DbSet<bina> bina { get; set; }
        public virtual DbSet<caddeSokak> caddeSokak { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<mahalle> mahalle { get; set; }
        public virtual DbSet<Mulkiyet> Mulkiyet { get; set; }
        public virtual DbSet<ParselBeyan> ParselBeyan { get; set; }
        public virtual DbSet<ParselHaciz> ParselHaciz { get; set; }
        public virtual DbSet<ParselIpotek> ParselIpotek { get; set; }
        public virtual DbSet<ParselIrtifak> ParselIrtifak { get; set; }
        public virtual DbSet<ParselIsgalci> ParselIsgalci { get; set; }
        public virtual DbSet<ParselMalik> ParselMalik { get; set; }
        public virtual DbSet<ParselMalikRelation> ParselMalikRelation { get; set; }
        public virtual DbSet<sahiplikDurum> sahiplikDurum { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tasinmazTürü> tasinmazTürü { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRoleRelation> UserRoleRelation { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<tapuMahalle> tapuMahalle { get; set; }
        public virtual DbSet<parsel> parsel { get; set; }
        public virtual DbSet<ParselSerh> ParselSerh { get; set; }
    }
}
