//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CityExperDb2Entities : DbContext
    {
        public CityExperDb2Entities()
            : base("name=CityExperDb2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ada> ada { get; set; }
        public virtual DbSet<bagimsiz> bagimsiz { get; set; }
        public virtual DbSet<caddeSokak> caddeSokak { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<mahalle> mahalle { get; set; }
        public virtual DbSet<parsel> parsel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tapuMahalle> tapuMahalle { get; set; }
        public virtual DbSet<tasinmaz> tasinmaz { get; set; }
    }
}
