//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParselMalikRelation
    {
        public int Id { get; set; }
        public Nullable<int> FkParselId { get; set; }
        public Nullable<int> FkParselMalikId { get; set; }
    
        public virtual ParselMalik ParselMalik { get; set; }
        public virtual parsel parsel { get; set; }
    }
}
