//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParselMalik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParselMalik()
        {
            this.ParselMalikRelation = new HashSet<ParselMalikRelation>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<int> Tc { get; set; }
        public string BabaAdi { get; set; }
        public string HisseOrani { get; set; }
        public string HisseMiktari { get; set; }
        public string EdinmeSebebi { get; set; }
        public Nullable<System.DateTime> ParselEdinmeTarihi { get; set; }
        public Nullable<int> ParselNo { get; set; }
        public string ParselMalikAdi { get; set; }
        public string ParselMalikSoyadi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParselMalikRelation> ParselMalikRelation { get; set; }
    }
}
