//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParselSerh
    {
        public int Id { get; set; }
        public Nullable<int> FkParselId { get; set; }
        public Nullable<System.DateTime> ParselSerhTarih { get; set; }
        public string ParselSerhAciklama { get; set; }
        public string ParselSerhYevmiyeNo { get; set; }
    
        public virtual parsel parsel { get; set; }
    }
}
