//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasinmaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tasinmaz()
        {
            this.bagimsiz = new HashSet<bagimsiz>();
        }
    
        public int tasinmaz_id { get; set; }
        public string kapıNo { get; set; }
        public int il_id { get; set; }
        public int ilce_id { get; set; }
        public int mahalle_id { get; set; }
        public int tapumahalle_id { get; set; }
        public int caddeSokak_id { get; set; }
        public int ada_id { get; set; }
        public int parsel_id { get; set; }
        public int binaNo { get; set; }
        public int binaYaşı { get; set; }
        public decimal rayicBedel { get; set; }
    
        public virtual ada ada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bagimsiz> bagimsiz { get; set; }
        public virtual caddeSokak caddeSokak { get; set; }
        public virtual il il { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual mahalle mahalle { get; set; }
        public virtual parsel parsel { get; set; }
        public virtual tapuMahalle tapuMahalle { get; set; }
    }
}
