//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasinmazTürü
    {
        public int tasinmazTür_id { get; set; }
        public string tasimazTürAd { get; set; }
        public Nullable<int> bina_id { get; set; }
        public Nullable<int> bagimsiz_id { get; set; }
    }
}
