//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityExperWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleRelation
    {
        public int Id { get; set; }
        public Nullable<int> FkUserId { get; set; }
        public Nullable<int> FkUserRoleId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual Users Users { get; set; }
    }
}
